### ISSUE TITLE
different Single Channel SDF method

### ISSUE THREAD

**Issue by Detector-I** [XrizZ/GLFontLibrary#1]
Hi, thank you for your work
Currently I need to create a a SDF font
I know there is plenty of options for doing it but I need it to be bmfont compatible, so my options are limited
The only thing that I found was heiro, it kinda works but it miss something that I need... It miss the force offset to zero option that original bmfont have... But I need this option
So can you help me with it?

**Comment by XrizZ** [comment]
Hi @Detector-I , thank you for your interest in my project.

If a single channel SDF font is sufficient, you can indeed use BMfont. But as a second step then use tools like imagemagick to get the sdf texture. I reckon that some amount of custom code will be necessary in your project to switch between "normal" and sdf rendering though. Have a look at my project page, I give any example for bmfont and sdfs there. It worked well for me and the result is BMfont compatible while also creating an sdf and non-sdf texture file.

The force offset to zero option may be missing as the sdf texture needs more space between characters to correctly encode the font. Just a guess though.

Hope this helps.

**Comment by Detector-I** [comment]
> Hi @Detector-I , thank you for your interest in my project.
> 
> If a single channel SDF font is sufficient, you can indeed use BMfont. But as a second step then use tools like imagemagick to get the sdf texture. I reckon that some amount of custom code will be necessary in your project to switch between "normal" and sdf rendering though. Have a look at my project page, I give any example for bmfont and sdfs there. It worked well for me and the result is BMfont compatible while also creating an sdf and non-sdf texture file.
> 
> The force offset to zero option may be missing as the sdf texture needs more space between characters to correctly encode the font. Just a guess though.
> 
> Hope this helps.

Thank you for answering
In the readme you said the current method need to change some of values in the font mapping itself in order to get it to work, and you also said you found another better method for generate sdf font, you mentioned that you maybe share it another time... I'm mostly interested in that because I want to keep manual editing away as far as I can...
About rendering I don't have any problem, my environment already support it

**Comment by XrizZ** [comment]
Ok, I see. These days, I think the easiest way is to use https://soimy.github.io/msdf-bmfont-xml/ they have a commandline parameter for switching between single and multichannel SDFs in their tool. Its the best method I know for SDF+BMfont format. If you find a another way though, please let me know and I'll add it to the tutorial in my project readme :)

**Comment by Detector-I** [comment]
> Ok, I see. These days, I think the easiest way is to use https://soimy.github.io/msdf-bmfont-xml/ they have a commandline parameter for switching between single and multichannel SDFs in their tool. Its the best method I know for SDF+BMfont format. If you find a another way though, please let me know and I'll add it to the tutorial in my project readme :)

Thank you, seems like a good alternative.
But sadly even this don't support forcing offset to zero...
I think I need to hack something together with the existing tools...
