### ISSUE TITLE
dircect run exist error,can you help me?thanks

### ISSUE THREAD

**Issue by Haidiye00** [XrizZ/GLFontLibrary#2]
![image](https://github.com/user-attachments/assets/6eccf163-5bd0-4966-924e-d52c605e92ce)

**Comment by XrizZ** [comment]
Thank you for the info @Haidiye00. Since its just a warning, I won't take any action right now, but I'll add it to my todo list. If you want to run the code, I would recommend disabling warnings as errors in your visual studio instance. Or using a different file loading routine.
